# Generated by Django 4.2.5 on 2023-09-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('link', models.URLField(verbose_name='Ссылка')),
                ('duration', models.DurationField(verbose_name='Продолжительнось')),
                ('product', models.ManyToManyField(blank=True, to='products.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Продолжительность',
                'verbose_name_plural': 'Продолжительности',
            },
        ),
    ]
