# Generated by Django 4.2.5 on 2023-09-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_userlesson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AddField(
            model_name='userlesson',
            name='last_watched',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последенго просмотра'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.DurationField(default=None, verbose_name='Продолжительнось'),
        ),
    ]
