# Generated by Django 4.2.5 on 2023-09-25 16:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessons', '0003_alter_lesson_options_userlesson_last_watched_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserLesson',
            new_name='UserLessonViewed',
        ),
    ]
