# Generated by Django 4.2.5 on 2023-09-25 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_students_alter_product_owner'),
        ('lessons', '0004_rename_userlesson_userlessonviewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='product',
        ),
        migrations.AddField(
            model_name='lesson',
            name='product',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='products.product', verbose_name='Урок'),
        ),
    ]
